/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zlahrouni.passwordgenerator;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PassGen extends javax.swing.JFrame {

    //Flags for checkbox
    boolean fLower, fUpper, fNum, fSymb ;
    
    String symbolsChar, numberChar, upperChar, lowerChar;
    /**
     * Creates new form PassGen
     */
    public PassGen() {
        initComponents();
        lowerChar = "abcdefghijklmnopuvwxyz";
        upperChar = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        numberChar = "0123456789";
        symbolsChar = "*@#+%(),;:\"&?./";
        fSymb = false;
        fNum = false;
        fUpper = false;
        fLower = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        OnButtonGenerateClick = new javax.swing.JButton();
        lowCharBox = new javax.swing.JCheckBox();
        uppCharBox = new javax.swing.JCheckBox();
        numBox = new javax.swing.JCheckBox();
        symBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passLength = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Generator");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("Password Generator");

        OnButtonGenerateClick.setText("Generate");
        OnButtonGenerateClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnButtonGenerateClickActionPerformed(evt);
            }
        });

        lowCharBox.setSelected(true);
        lowCharBox.setText("(e.g. abcdef)");

        uppCharBox.setSelected(true);
        uppCharBox.setText("(e.g. ABCDEF)");

        numBox.setSelected(true);
        numBox.setText("(e.g. 123456)");

        symBox.setSelected(true);
        symBox.setText(" (e.g. *@#+%)");
        symBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Lowercase Characters :");

        jLabel3.setText("Uppercase Characters :");

        jLabel4.setText("Numbes:");

        jLabel5.setText("Symbols:");

        jLabel6.setText("Password Length:");

        passLength.setText("8");

        txtResult.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(OnButtonGenerateClick, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(155, 155, 155))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(passLength, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uppCharBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowCharBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(symBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 53, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lowCharBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uppCharBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(symBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(OnButtonGenerateClick, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void symBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symBoxActionPerformed

    private void OnButtonGenerateClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnButtonGenerateClickActionPerformed
        if(lowCharBox.isSelected())
        {
            fLower = true;
        }
        if(uppCharBox.isSelected())
        {
            fUpper = true;
        }
        if(numBox.isSelected())
        {
            fNum = true;
        }
        if(symBox.isSelected())
        {
            fSymb = true;
        }
        
        int length = Integer.parseInt(passLength.getText());
        if(length>25)
        {
            JOptionPane.showMessageDialog(this, "Min Value is 8 \nMax Value is 25 ", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            passLength.setText("25");
        }
        else if(length<8)
        {
            JOptionPane.showMessageDialog(this, "Min Value is 8 \nMax Value is 25 ", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            passLength.setText("8");
        }
        else 
        {
            passGenerator(length);
        }
        // init the flags for next time we click on button
        fNum = false;
        fSymb = false;
        fUpper = false;
        fLower = false;
    }//GEN-LAST:event_OnButtonGenerateClickActionPerformed
    // My Functions :
    public void passGenerator(int len){
        String password = "";
        int idx;
        for(int i=0; i<len; i++)
        {
            int rand = (int)(4* Math.random());
            
            switch(rand) {
                case 0:
                    if(fNum)
                    {
                        
                        password += String.valueOf((int)(0+(Math.random()*9)));
                        
                        break;
                    }
                    else // if num checkbox is not selected we gonna check the next number
                        rand++;
                case 1: 
                    if(fLower)
                    {
                        idx = (int)(lowerChar.length() * Math.random());
                        password += String.valueOf(lowerChar.charAt(idx));
                        break;
                    }
                    else
                        rand++;
                case 2:
                    if(fUpper)
                    {
                        idx = (int)(upperChar.length() * Math.random());
                        password += String.valueOf(upperChar.charAt(idx));
                        break;
                    }
                    else
                        rand++;
                case 3: 
                    if(fSymb)
                    {
                        idx = (int)(symbolsChar.length() * Math.random());
                        password += String.valueOf(symbolsChar.charAt(idx));
                        break;
                    }
                    else
                        rand = 0;
                //default: JOptionPane.showMessageDialog(this, "Unknown Error ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        txtResult.setText(password);
        /*
        StringBuilder st = new StringBuilder(); 
        Random rand = new Random();
        while(0<len--){
            st.append(validChar.charAt(rand.nextInt(validChar.length())));
        }
        txtResult.setText(st.toString());
        */
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OnButtonGenerateClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox lowCharBox;
    private javax.swing.JCheckBox numBox;
    private javax.swing.JTextField passLength;
    private javax.swing.JCheckBox symBox;
    private javax.swing.JTextField txtResult;
    private javax.swing.JCheckBox uppCharBox;
    // End of variables declaration//GEN-END:variables
}
